sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master

php:
  - 5.6

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
